---
title: "STATS 100 project"
author: "Jonathan Calixto, Baird Johnson, Christian Palomo"
output: html_notebook
---


```{r}
suppressPackageStartupMessages(library(knitr))
suppressPackageStartupMessages(library(latex2exp))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(glmnet))
suppressPackageStartupMessages(library(predtools))
suppressPackageStartupMessages(library(psych))
suppressPackageStartupMessages(library(readxl))
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

Deca_data = read_excel("2022_Decathlon_Men_senior.xlsx")
view(Deca_data)



```

```{r}


`100m_points` = round(25.4347 * (18 - as.numeric(Deca_data$`100m`)) ** 1.81)

LJ_points = round(0.14354 * (as.numeric(Deca_data$LJ) - 220) ** 1.4)

SP_points = round(51.39 * (as.numeric(Deca_data$SP) - 1.5) ** 1.05)

HJ_points = round(0.8465 * (as.numeric(Deca_data$HJ) - 75) ** 1.42)

`400m_points` = round(1.53775 * (82 - as.numeric(Deca_data$`400m`)) ** 1.81)

`110H_points` = round(5.74352 * (28.65 - as.numeric(Deca_data$`110H`)) ** 1.92)

DT_points = round(12.91 * (as.numeric(Deca_data$DT) - 4) ** 1.1)
DT_points[is.nan(DT_points)] <- 0

PV_points = round(0.2797 * (as.numeric(Deca_data$PV) - 100) ** 1.35)
PV_points[is.nan(PV_points)] <- 0

JT_points = round(10.14 * (as.numeric(Deca_data$JT) - 7) ** 1.08)


`1500m_results` = 60 * as.numeric(Deca_data$`1500m_minutes`) + as.numeric(Deca_data$`1500m_seconds`)
`1500m_points` = round(0.03768 * (480 - `1500m_results`) ** 1.85)

Deca_points_data <- data.frame(`100m_points`, LJ_points, SP_points, HJ_points, `400m_points`, `110H_points`, DT_points, PV_points, JT_points, `1500m_points`)

Deca_points_data$total = Deca_data$Total_score
Deca_points_data$name = Deca_data$Last

dim(Deca_points_data)


view(Deca_points_data)



```

```{r}

Deca_points_data$technique_events = Deca_points_data$X110H_points + Deca_points_data$DT_points + Deca_points_data$PV_points + Deca_points_data$JT_points

Deca_points_data$technique_percentage = Deca_points_data$technique_events / Deca_points_data$total

X100m_percentage = Deca_points_data$X100m_points / Deca_points_data$total
LJ_percentage = Deca_points_data$LJ_points / Deca_points_data$total
SP_percentage = Deca_points_data$SP_points / Deca_points_data$total
HJ_percentage = Deca_points_data$HJ_points / Deca_points_data$total
X400m_percentage = Deca_points_data$X400m_points / Deca_points_data$total
X110H_percentage = Deca_points_data$X110H_points / Deca_points_data$total
DT_percentage = Deca_points_data$DT_points / Deca_points_data$total
PV_percentage = Deca_points_data$PV_points / Deca_points_data$total
JT_percentage = Deca_points_data$JT_points / Deca_points_data$total
X1500m_percentage = Deca_points_data$X1500m_points / Deca_points_data$total


Deca_percentages <- data.frame(X100m_percentage, LJ_percentage, SP_percentage, HJ_percentage, X400m_percentage, X110H_percentage, DT_percentage, PV_percentage, JT_percentage, X1500m_percentage)

view(Deca_percentages)

df$events = colnames((Deca_points_data)[1:10])

means = c()
sds = c()

for (col in Deca_percentages) {
  
  means = c(means, mean(col))
  sds = c(sds, sd(col))
}

view(means)

df$mean_percentages = means
df$sd_percentages = sds

view(df)

```

```{r}

ggplot(df, aes(x = events, y = mean_percentages, group = 1)) + geom_point() + ylim(0.05, 0.15) + geom_errorbar(width = 0.1, aes(ymin = mean_percentages - sd_percentages, ymax = mean_percentages + sd_percentages)) + theme(axis.text.x = element_text(angle = 45)) + labs(title = "Average point contribution per event")

```

``` {r}


lm_model_1 <- lm(X400m_points ~ X100m_points, data = Deca_points_data)
summary(lm_model_1)

lm_model_2 <- lm(JT_points ~ PV_points, data = Deca_points_data)
summary(lm_model_2)

lm_model_3 <- lm(JT_points ~ X100m_points, data = Deca_points_data)
summary(lm_model_3)

lm_model_4 <- lm(X1500m_points ~ X400m_points, data = Deca_points_data)
summary(lm_model_4)

print(lm_model_1$coefficients)

ggplot(data = Deca_points_data, aes(x = X100m_points, y = X400m_points)) + geom_point() + geom_abline(slope = lm_model_1$coef[2], intercept = lm_model_1$coef[1], color = 'red')

ggplot(data = Deca_points_data, aes(x = PV_points, y = JT_points)) + geom_point() + geom_abline(slope = lm_model_2$coef[2], intercept = lm_model_2$coef[1], color = 'red')

ggplot(data = Deca_points_data, aes(x = X100m_points, y = JT_points)) + geom_point() + geom_abline(slope = lm_model_3$coef[2], intercept = lm_model_3$coef[1], color = 'red')

ggplot(data = Deca_points_data, aes(x = X400m_points, y = X1500m_points)) + geom_point() + geom_abline(slope = lm_model_4$coef[2], intercept = lm_model_4$coef[1], color = 'red')

```

``` {r}

# Perform linear regression for each event
for (event in colnames) {
  # Create a formula for the linear regression
  

  
  # Fit the linear regression model
  lm_model <- lm(total ~ event, data = Deca_points_data)
  
  print(length(event))
  print(length(total))
  
  # Print the regression results
  cat("Event:", event, "\n")
  print(summary(lm_model))
  cat("\n")
}
```